DATATYPES: dict[str, dict] = {
    "ST":  {"name": "String",                                          "description": "General string data."},
    "ID":  {"name": "Coded value (HL7 table)",                        "description": "Refers to a fixed HL7 table."},
    "IS":  {"name": "Coded value (user-defined table)",               "description": "Refers to a locally defined table."},
    "NM":  {"name": "Numeric",                                        "description": "Numeric value as a string."},
    "DT":  {"name": "Date",                                           "description": "YYYY[MM[DD]] format."},
    "TM":  {"name": "Time",                                           "description": "HH[MM[SS[.S[S[S[S]]]]]][+/-ZZZZ]."},
    "TS":  {"name": "Time Stamp",                                     "description": "Date and time, YYYYMMDDHHMMSS.SSSS."},
    "FT":  {"name": "Formatted Text",                                 "description": "String with embedded formatting commands."},
    "TX":  {"name": "Text Data",                                      "description": "Unformatted text."},
    "SI":  {"name": "Sequence ID",                                    "description": "Non-negative integer for sequencing."},
    "GTS": {"name": "General Timing Specification",                   "description": "Complex timing expression."},
    "CE":  {"name": "Coded Element",                                  "description": "Deprecated in v2.7; use CWE."},
    "CWE": {"name": "Coded with Exceptions",                         "description": "Coded field that allows text when no code exists."},
    "CNE": {"name": "Coded, No Exceptions",                          "description": "Coded field; code required."},
    "CX":  {"name": "Extended Composite ID",                         "description": "Identifier with assigning authority."},
    "XPN": {"name": "Extended Person Name",                          "description": "Family, given, middle, suffix, prefix."},
    "XAD": {"name": "Extended Address",                              "description": "Multi-component mailing address."},
    "XTN": {"name": "Extended Telecommunications Number",            "description": "Phone/fax with type codes."},
    "XCN": {"name": "Extended Composite ID and Name",               "description": "Person name + identifier (provider)."},
    "XON": {"name": "Extended Composite Name/ID for Organizations",  "description": "Organization name + ID."},
    "HD":  {"name": "Hierarchic Designator",                        "description": "Namespace identifier and universal ID."},
    "EI":  {"name": "Entity Identifier",                            "description": "Instance identifier with namespace."},
    "PL":  {"name": "Person Location",                              "description": "Point of care, room, bed, facility."},
    "PT":  {"name": "Processing Type",                              "description": "Processing ID and mode."},
    "MSG": {"name": "Message Type",                                 "description": "Message type and event code."},
    "VID": {"name": "Version Identifier",                           "description": "HL7 version and internationalization."},
    "CK":  {"name": "Composite ID with Check Digit",               "description": "Deprecated; use CX."},
    "CM":  {"name": "Composite",                                    "description": "Deprecated untyped composite field."},
    "DR":  {"name": "Date/Time Range",                             "description": "Start and end date/time."},
    "ED":  {"name": "Encapsulated Data",                           "description": "Binary or encoded data (e.g., PDF)."},
    "RP":  {"name": "Reference Pointer",                           "description": "Pointer to external data."},
    "TQ":  {"name": "Timing/Quantity",                            "description": "Deprecated in v2.7; complex order timing."},
    "SN":  {"name": "Structured Numeric",                         "description": "Numeric range or structured value."},
    "NA":  {"name": "Numeric Array",                              "description": "Series of numeric values."},
    "CF":  {"name": "Coded Element with Formatted Values",        "description": "CE with formatted text."},
    "FC":  {"name": "Financial Class",                            "description": "Financial class + effective date."},
    "MO":  {"name": "Money",                                      "description": "Monetary amount with currency code."},
    "PPN": {"name": "Performing Person Time Stamp",              "description": "Person name + when performed."},
    "SPS": {"name": "Specimen Source",                           "description": "Specimen source components."},
    "DTN": {"name": "Day Type and Number",                       "description": "Payer day type and count."},
    "CCD": {"name": "Charge Code and Date",                      "description": "Charge code with effective date."},
    "OG":  {"name": "Observation Grouper",                       "description": "Groups observations (v2.8+)."},
    "CP":  {"name": "Composite Price",                           "description": "Price with currency and price type."},
    "MA":  {"name": "Multiplexed Array",                        "description": "Multiple channels of numeric data."},
    "QSC": {"name": "Query Selection Criteria",                 "description": "Query filter criteria (deprecated)."},
    "RFR": {"name": "Reference Range",                          "description": "Observation reference range."},
    "VR":  {"name": "Value Range",                              "description": "Low-high range of values."},
    "DDI": {"name": "Daily Deductible Information",             "description": "Insurance deductible data."},
    "DIN": {"name": "Date and Institution Name",               "description": "Date + institution identifier."},
    "DLD": {"name": "Discharge to Location and Date",          "description": "Discharge location and date."},
    "DLT": {"name": "Delta",                                    "description": "Normal range delta check."},
    "NDL": {"name": "Name with Date and Location",             "description": "Name, date, and location composite."},
    "WVS": {"name": "Waveform Source",                         "description": "Waveform data source info."},
}
